{{- if not .Values.appSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terminus.fullname" . }}-app
  labels:
    {{- include "terminus.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-secret: {{ required "appSecret.value must be provided when appSecret.existingSecret is empty" .Values.appSecret.value | quote }}
{{- end }}
