{{- if .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "terminus.web.fullname" . }}
  labels:
    {{- include "terminus.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- end }}
  {{- $root := . -}}
  rules:
    {{- range .Values.web.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "terminus.web.fullname" $root }}
                port:
                  number: {{ $root.Values.web.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.web.ingress.tls }}
  tls:
    {{- toYaml .Values.web.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
