{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "terminus.redis.fullname" . }}
  labels:
    {{- include "terminus.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
  {{- with .Values.redis.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
  selector:
    {{- include "terminus.componentSelectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
  type: ClusterIP
{{- end }}
