{{- if and .Values.web.persistence.enabled (not .Values.web.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "terminus.web.fullname" . }}-uploads
  labels:
    {{- include "terminus.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
  {{- with .Values.web.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.web.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.web.persistence.size }}
  {{- if .Values.web.persistence.storageClass }}
  storageClassName: {{ .Values.web.persistence.storageClass }}
  {{- end }}
{{- end }}
